# Generated by Django 4.1.5 on 2023-01-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Middle name')),
                ('date_of_birth', models.CharField(blank=True, max_length=50, null=True, verbose_name='Date of birth')),
                ('patient_address', models.CharField(max_length=100, verbose_name='Address')),
                ('patient_contact', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telephone/Cellphone number')),
                ('guardian', models.CharField(blank=True, max_length=50, verbose_name='Guardian')),
                ('guardian_address', models.CharField(blank=True, max_length=100, verbose_name="Guardian's address")),
                ('guardian_telephone', models.CharField(blank=True, max_length=15, verbose_name="Guardian's Telephone/Cellphone number")),
            ],
        ),
    ]
