# Generated by Django 4.1.5 on 2023-01-19 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_patient_created_at_patient_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='student_number',
            field=models.CharField(default='00x-0000', max_length=10, verbose_name='Student Number'),
        ),
        migrations.CreateModel(
            name='PatientIllness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_name', models.CharField(max_length=20, verbose_name='Illness name')),
                ('past', models.CharField(max_length=50, verbose_name='Past medical history')),
                ('present', models.CharField(max_length=50, verbose_name='Current medical condition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illness', to='base.patient', verbose_name='Patient')),
            ],
        ),
    ]
