# Generated by Django 4.1.5 on 2023-01-19 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_patient_student_number_patientillness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_name', models.CharField(max_length=20, verbose_name='Illness name')),
                ('past', models.CharField(max_length=50, verbose_name='Past medical history')),
                ('present', models.CharField(max_length=50, verbose_name='Current medical condition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.patient', verbose_name='Patient')),
            ],
        ),
        migrations.DeleteModel(
            name='PatientIllness',
        ),
    ]
