# Generated by Django 4.1.5 on 2023-01-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_illness_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='illness_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Illness name'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='past',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Past medical history'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='present',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Current medical condition'),
        ),
    ]
