# Generated by Django 4.1.5 on 2023-01-19 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_illness_illness_name_alter_illness_past_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20, verbose_name='Year level')),
                ('height', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Height (cm)')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Weight (kg)')),
                ('eyes', models.CharField(max_length=20, verbose_name='Eyes')),
                ('r_vision', models.CharField(max_length=20, verbose_name='Right Vision')),
                ('l_vision', models.CharField(max_length=20, verbose_name='Left Vision')),
                ('ears', models.CharField(max_length=20, verbose_name='Ears')),
                ('nose', models.CharField(max_length=20, verbose_name='Nose')),
                ('throat', models.CharField(max_length=20, verbose_name='Throat')),
                ('mouth', models.CharField(max_length=20, verbose_name='Mouth')),
                ('neck', models.CharField(max_length=20, verbose_name='Neck')),
                ('extremities', models.CharField(max_length=20, verbose_name='Extremities')),
                ('heart_auscultation', models.CharField(max_length=20, verbose_name='Heart Auscultation')),
                ('skin', models.CharField(max_length=20, verbose_name='Skin')),
                ('nails', models.CharField(max_length=20, verbose_name='Nails')),
                ('head', models.CharField(max_length=20, verbose_name='Head')),
                ('personal_hygiene', models.CharField(max_length=20, verbose_name='Personal Hygiene')),
                ('general_health', models.CharField(max_length=20, verbose_name='General Health')),
                ('other_remarks', models.TextField(blank=True, null=True, verbose_name='Other Remarks')),
                ('name_of_physician', models.CharField(max_length=20, verbose_name='Name of Physician')),
                ('code_of_rating', models.CharField(choices=[('O', 'Satisfaction'), ('X', 'Requires attention'), ('P', 'Parents notified')], default='O', max_length=1, verbose_name='Code of Rating')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='base.patient')),
            ],
        ),
    ]
