# Generated by Django 4.1.5 on 2023-01-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_patientdiagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='ears',
            field=models.CharField(default='', max_length=20, verbose_name='Ears'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='extremities',
            field=models.CharField(default='', max_length=20, verbose_name='Extremities'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='eyes',
            field=models.CharField(default='', max_length=20, verbose_name='Eyes'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='general_health',
            field=models.CharField(default='', max_length=20, verbose_name='General Health'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='head',
            field=models.CharField(default='', max_length=20, verbose_name='Head'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='heart_auscultation',
            field=models.CharField(default='', max_length=20, verbose_name='Heart Auscultation'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='height',
            field=models.DecimalField(decimal_places=1, default='', max_digits=4, verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='l_vision',
            field=models.CharField(default='', max_length=20, verbose_name='Left Vision'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='level',
            field=models.CharField(default='', max_length=20, verbose_name='Year level'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='mouth',
            field=models.CharField(default='', max_length=20, verbose_name='Mouth'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='nails',
            field=models.CharField(default='', max_length=20, verbose_name='Nails'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='name_of_physician',
            field=models.CharField(default='', max_length=20, verbose_name='Name of Physician'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='neck',
            field=models.CharField(default='', max_length=20, verbose_name='Neck'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='nose',
            field=models.CharField(default='', max_length=20, verbose_name='Nose'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='other_remarks',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Other Remarks'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='personal_hygiene',
            field=models.CharField(default='', max_length=20, verbose_name='Personal Hygiene'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='r_vision',
            field=models.CharField(default='', max_length=20, verbose_name='Right Vision'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='skin',
            field=models.CharField(default='', max_length=20, verbose_name='Skin'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='throat',
            field=models.CharField(default='', max_length=20, verbose_name='Throat'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='weight',
            field=models.DecimalField(decimal_places=1, default='', max_digits=4, verbose_name='Weight (kg)'),
        ),
    ]
