# Generated by Django 4.1.5 on 2023-01-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_patientdiagnostic_ears_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='ears',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ears'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='extremities',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Extremities'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='eyes',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Eyes'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='general_health',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='General Health'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='head',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Head'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='heart_auscultation',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Heart Auscultation'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='l_vision',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Left Vision'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='level',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Year level'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='mouth',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mouth'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='nails',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nails'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='name_of_physician',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Name of Physician'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='neck',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Neck'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='nose',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nose'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='other_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Other Remarks'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='personal_hygiene',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Personal Hygiene'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='r_vision',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Right Vision'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='skin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Skin'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='throat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Throat'),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weight (kg)'),
        ),
    ]
