# Generated by Django 4.1.5 on 2023-01-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_patientdiagnostic_ears_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdiagnostic',
            name='level',
        ),
    ]
