# Generated by Django 4.1.5 on 2023-01-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_patientdiagnostic_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdiagnostic',
            name='lung_auscultation',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lung Auscultation'),
        ),
    ]
