# Generated by Django 4.1.5 on 2023-01-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_patientdiagnostic_lung_auscultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, default='', max_digits=4, null=True, verbose_name='Height (cm)'),
        ),
    ]
