# Generated by Django 4.1.5 on 2023-01-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_patientdiagnostic_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Height (cm)'),
        ),
    ]
