# Generated by Django 4.1.5 on 2023-01-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_patientdata_delete_patientdiagnostic'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorsLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('student_number', models.CharField(max_length=20)),
                ('year_and_level', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
