# Generated by Django 4.1.5 on 2023-01-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_visitorslogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitorslogs',
            old_name='year_and_level',
            new_name='year_or_level',
        ),
        migrations.AlterField(
            model_name='visitorslogs',
            name='program',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
