# Generated by Django 4.1.5 on 2023-01-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_rename_year_and_level_visitorslogs_year_or_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorslogs',
            name='program',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
