# Generated by Django 4.1.5 on 2023-01-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_patientclinicrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientClinicRecord',
            new_name='Record',
        ),
    ]
