# Generated by Django 4.1.5 on 2023-01-22 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_record_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='base.patient'),
        ),
    ]
