# Generated by Django 4.1.5 on 2023-01-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_record_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorsLogs',
        ),
        migrations.AddField(
            model_name='record',
            name='action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
