# Generated by Django 4.1.5 on 2023-01-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_delete_visitorslogs_record_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='treatments_medication',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
