# Generated by Django 4.1.5 on 2023-01-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_remove_patient_gender_patient_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
