# Generated by Django 4.1.3 on 2023-02-07 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_permissions_alter_illness_options_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.patient'),
        ),
    ]
