# Generated by Django 4.1.3 on 2023-02-07 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_permissions_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='base.patient'),
        ),
    ]
