# Generated by Django 4.1.3 on 2023-02-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_permissions_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='parents_name',
            field=models.CharField(max_length=50),
        ),
    ]
